-- Data ingestion: unstructured sources in, structured rows out, the graph built from the rows.
--
-- THE GAP. Unstructured material keeps arriving: workshop notes, slide decks, transcripts,
-- emails. The first example is the 2026 workshop's Appendix A, a sensor and device registry. Until
-- now the only routes into the database were the NIH harvesters (structured at the source) and
-- curators typing. Material like Appendix A therefore ended up either nowhere or in a checked-in
-- file the graph read directly. That makes the file a second source of truth (Principle XI), with
-- no audit trail (Principle X), that the people who own the data cannot correct.
--
-- THE SHAPE. Four stages, each a table, so every value can be traced back to the sentence it came
-- from:
--   ingestion_sources  one row per raw document: what it is, where it lives, when it came in.
--   ingestion_records  one row per extracted record. The extractor (a person or an LLM) writes a
--                      payload matching the record kind's JSON Schema (ingest/kinds/*.schema.json).
--                      Each record carries its review flags and status. Curator-only: payloads
--                      quote the source.
--   promote_ingestion_record()  validates a payload and writes it into the domain tables, linking
--                      each domain row back to the record and the source. Re-promoting updates in place.
--   domain tables      the system of record. The KG exporter reads only these.
--
-- THE FIRST RECORD KIND: sensor_deployment. One device as used on one award, which is what Appendix
-- A holds. These rows are what the exporter turns into W3C SOSA/SSN, see kg/sosa/README.md:
--   observable_properties          the vocabulary: what can be observed or actuated (pupil
--                                  diameter, skin conductance, responsive stimulation), aligned
--                                  to device_categories.
--   sensor_deployments             one row per (award, device as named): grant (nullable when
--                                  unresolved), how the award was matched, how the model is known,
--                                  whether a presenter confirmed it aloud.
--   sensor_deployment_devices      deployment -> device_models (the catalogue entry), 0..n.
--   sensor_deployment_properties   deployment -> observable_properties, as 'observes' or 'actuates'.
--   sensor_deployment_presenters   presenter NAMES, curator-only. Anonymous readers and the public
--                                  export see a role ("Postdoc, Suthana lab"), never a student's name,
--                                  and certainly not a guessed one.
--
-- Two invariants of the SOSA shapes are enforced here as CHECKs, so the database refuses what the
-- graph would flag: grant_match 'unresolved' if and only if there is no grant (S-4), and a row no
-- presenter spoke to must say what needs verifying (S-8).
--
-- The vocabulary and the Appendix A records are seeded by 20261006120100, which is generated by
-- ingest/to_sql.py.
--
-- Apply MANUALLY in the KG SQL editor (vpexxhfpvghlejljwpvt), then 20261006120100.

SELECT public.set_actor('migration:20261006120000_data_ingestion');

-- ── 1. Sources ───────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.ingestion_sources (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug           text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9][a-z0-9-]*$'),
  kind           text NOT NULL CHECK (kind IN ('workshop_notes', 'slide_deck', 'transcript', 'email',
                                               'form_response', 'registry_table', 'document', 'other')),
  title          text NOT NULL,
  description    text,
  origin_url     text,
  storage_path   text,
  content_sha256 text,
  received_at    timestamptz NOT NULL DEFAULT now(),
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.ingestion_sources IS
  'One row per raw document that entered through data ingestion (ingest/README.md). The slug names it in the KG (bid:sosa/source/<slug>). storage_path points at the raw file when it is kept in Storage. Metadata only and readable by anyone; the extracted content is in ingestion_records, which is curator-only.';

-- ── 2. Records ───────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.ingestion_records (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_id      uuid NOT NULL REFERENCES public.ingestion_sources(id) ON DELETE CASCADE,
  record_kind    text NOT NULL CHECK (record_kind IN ('sensor_deployment')),
  source_locator text NOT NULL,
  payload        jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  extracted_by   text NOT NULL CHECK (extracted_by ~ '^(human|llm):.+'),
  source_class   text NOT NULL REFERENCES public.source_classes(code),
  status         text NOT NULL DEFAULT 'pending_review'
                   CHECK (status IN ('pending_review', 'accepted', 'rejected', 'promoted')),
  review_flags   text[] NOT NULL DEFAULT '{}',
  review_note    text,
  reviewed_by    text,
  reviewed_at    timestamptz,
  promoted_table text,
  promoted_id    uuid,
  promoted_at    timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_id, record_kind, source_locator)
);

CREATE INDEX IF NOT EXISTS idx_ingestion_records_status ON public.ingestion_records (record_kind, status);

COMMENT ON TABLE public.ingestion_records IS
  'One structured record extracted from an ingestion source. payload matches ingest/kinds/<record_kind>.schema.json. source_locator is where in the source it came from (a row id, slide or page). extracted_by is human:<what> or llm:<model>, and source_class grades it (curator_fill for a person, llm_extract for a model). review_flags list what a curator should check. promote_ingestion_record() writes it to the domain tables and fills promoted_*.';
COMMENT ON COLUMN public.ingestion_records.status IS
  'pending_review: has review flags or came from a machine. accepted: a curator (or a clean human extraction) cleared it. rejected: never promoted. promoted: written to promoted_table/promoted_id; flags still stand until a curator clears them.';

-- ── 3. Vocabulary ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.observable_properties (
  key              text PRIMARY KEY CHECK (key ~ '^[a-z][a-z0-9_]*$'),
  property_kind    text NOT NULL DEFAULT 'observable' CHECK (property_kind IN ('observable', 'actuatable')),
  label            text NOT NULL,
  definition       text,
  foi_kind         text CHECK (foi_kind IN ('subject', 'environment')),
  category_key     text REFERENCES public.device_categories(key) ON UPDATE CASCADE ON DELETE SET NULL,
  category_measure text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CHECK ((property_kind = 'observable') = (foi_kind IS NOT NULL))
);

COMMENT ON TABLE public.observable_properties IS
  'What a sensor can observe (sosa:ObservableProperty) or an actuator act on (sosa:ActuatableProperty). foi_kind says whose property it is: the study subject or their environment. category_key/category_measure align it to a device category and to one of that category''s measures values.';

-- ── 4. Deployments ───────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.sensor_deployments (
  id                       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  grant_id                 uuid REFERENCES public.grants(id) ON DELETE SET NULL,
  award_label              text NOT NULL,
  grant_match              text NOT NULL
                             CHECK (grant_match IN ('stated', 'pi_roster', 'institution', 'title', 'ambiguous', 'unresolved')),
  grant_note               text,
  label_as_named           text NOT NULL,
  system_kind              text NOT NULL CHECK (system_kind IN ('sensor', 'platform', 'sensor_actuator')),
  presenter_role           text,
  presenter_present        boolean NOT NULL,
  verify_note              text,
  manufacturer_recorded    text,
  manufacturer_hq_recorded text,
  model_recorded           text,
  model_status             text NOT NULL CHECK (model_status IN ('compiled', 'inferred', 'candidates', 'custom', 'unspecified')),
  measures_recorded        text,
  source_id                uuid REFERENCES public.ingestion_sources(id) ON DELETE SET NULL,
  source_locator           text,
  ingestion_record_id      uuid REFERENCES public.ingestion_records(id) ON DELETE SET NULL,
  confirmed_by             text,
  confirmed_at             timestamptz,
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now(),
  UNIQUE (award_label, label_as_named),
  CONSTRAINT sensor_deployments_unresolved_iff_no_grant CHECK ((grant_match = 'unresolved') = (grant_id IS NULL)),
  CONSTRAINT sensor_deployments_unconfirmed_is_flagged CHECK (presenter_present OR verify_note IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_sensor_deployments_grant ON public.sensor_deployments (grant_id);

COMMENT ON TABLE public.sensor_deployments IS
  'One device as used on one award: a sosa:Sensor or sosa:Platform deployed (ssn:Deployment) on the grant''s study subjects. Filled by promote_ingestion_record(); read by the KG exporter. The *_recorded columns hold what the source said, kept beside the catalogue link so a disagreement stays visible.';
COMMENT ON COLUMN public.sensor_deployments.grant_match IS
  'How award_label was resolved to grant_id: stated in the source; pi_roster (presenter or lab is a named lead); institution (the only BBQS grant there); title; ambiguous (best of several, see grant_note); unresolved (no grant_id).';
COMMENT ON COLUMN public.sensor_deployments.model_status IS
  'How the model is known: compiled (from vendor sources after the fact, not the source document), inferred, candidates (several named), custom (in-house), unspecified.';

CREATE TABLE IF NOT EXISTS public.sensor_deployment_devices (
  deployment_id   uuid NOT NULL REFERENCES public.sensor_deployments(id) ON DELETE CASCADE,
  device_model_id uuid NOT NULL REFERENCES public.device_models(id) ON DELETE CASCADE,
  PRIMARY KEY (deployment_id, device_model_id)
);

CREATE TABLE IF NOT EXISTS public.sensor_deployment_properties (
  deployment_id uuid NOT NULL REFERENCES public.sensor_deployments(id) ON DELETE CASCADE,
  property_key  text NOT NULL REFERENCES public.observable_properties(key) ON UPDATE CASCADE,
  role          text NOT NULL CHECK (role IN ('observes', 'actuates')),
  PRIMARY KEY (deployment_id, property_key, role)
);

-- A sensor observes an observable property and an actuator acts on an actuatable one. Mixing them
-- up would type a stimulation as something measured.
CREATE OR REPLACE FUNCTION public.check_sensor_deployment_property_kind()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $fn$
DECLARE _kind text;
BEGIN
  SELECT property_kind INTO _kind FROM public.observable_properties WHERE key = NEW.property_key;
  IF (NEW.role = 'observes') <> (_kind = 'observable') THEN
    RAISE EXCEPTION 'Property % is %, so it cannot be used as role %', NEW.property_key, _kind, NEW.role;
  END IF;
  RETURN NEW;
END;
$fn$;

DROP TRIGGER IF EXISTS trg_sensor_deployment_property_kind ON public.sensor_deployment_properties;
CREATE TRIGGER trg_sensor_deployment_property_kind
  BEFORE INSERT OR UPDATE ON public.sensor_deployment_properties
  FOR EACH ROW EXECUTE FUNCTION public.check_sensor_deployment_property_kind();

CREATE TABLE IF NOT EXISTS public.sensor_deployment_presenters (
  deployment_id        uuid PRIMARY KEY REFERENCES public.sensor_deployments(id) ON DELETE CASCADE,
  presenter_name       text NOT NULL,
  name_needs_verifying boolean NOT NULL DEFAULT false,
  investigator_id      uuid REFERENCES public.investigators(id) ON DELETE SET NULL,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.sensor_deployment_presenters IS
  'Who spoke to a deployment, by name. Curator-only, because presenters are often students and some names in the source were guesses (name_needs_verifying). investigator_id is set only once the person is confirmed. Never part of an ingestion payload, so never in the repo or the anon export.';

-- ── 5. Access ────────────────────────────────────────────────────────────────────────────────
-- Public: what was ingested from where, and the domain rows. Curator-only: payloads and names.
DO $do$
DECLARE
  t text;
  public_read text[] := ARRAY['ingestion_sources', 'observable_properties', 'sensor_deployments',
                              'sensor_deployment_devices', 'sensor_deployment_properties'];
  curator_only text[] := ARRAY['ingestion_records', 'sensor_deployment_presenters'];
BEGIN
  FOREACH t IN ARRAY public_read || curator_only LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO authenticated', t);
    EXECUTE format('GRANT ALL ON public.%I TO service_role', t);
    EXECUTE format('DROP POLICY IF EXISTS "%1$s writable by curators" ON public.%1$I', t);
    EXECUTE format('CREATE POLICY "%1$s writable by curators" ON public.%1$I FOR ALL TO authenticated '
                   'USING (public.is_curator_or_admin(auth.uid())) '
                   'WITH CHECK (public.is_curator_or_admin(auth.uid()))', t);
    -- Audit floor (Principle X): every write to every one of these tables is attributable.
    EXECUTE format('DROP TRIGGER IF EXISTS trg_audit_%1$s ON public.%1$I', t);
    EXECUTE format('CREATE TRIGGER trg_audit_%1$s AFTER INSERT OR UPDATE OR DELETE ON public.%1$I '
                   'FOR EACH ROW EXECUTE FUNCTION public.log_data_change()', t);
  END LOOP;
  FOREACH t IN ARRAY public_read LOOP
    EXECUTE format('GRANT SELECT ON public.%I TO anon', t);
    EXECUTE format('DROP POLICY IF EXISTS "%1$s readable by all" ON public.%1$I', t);
    EXECUTE format('CREATE POLICY "%1$s readable by all" ON public.%1$I FOR SELECT USING (true)', t);
  END LOOP;
  FOREACH t IN ARRAY ARRAY['ingestion_sources', 'ingestion_records', 'observable_properties',
                           'sensor_deployments', 'sensor_deployment_presenters'] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_%1$s_updated ON public.%1$I', t);
    EXECUTE format('CREATE TRIGGER trg_%1$s_updated BEFORE UPDATE ON public.%1$I '
                   'FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column()', t);
  END LOOP;
END $do$;

-- ── 6. Provenance coverage ───────────────────────────────────────────────────────────────────
-- ingestion_records is intake state, a decision about data rather than data, like access_requests.
-- Its payload is graded where it lands, in sensor_deployments. The list below is
-- 20260923120000's, unchanged except for the one addition.
CREATE OR REPLACE FUNCTION public.provenance_excluded_tables()
RETURNS text[] LANGUAGE sql IMMUTABLE AS $fn$
  SELECT ARRAY[
    -- the mechanism itself: recording provenance about provenance recurses
    'field_provenance', 'source_classes',
    -- append-only logs: a log row is already a historical assertion, with no current value to grade
    'data_audit_log', 'auth_audit_log', 'edit_history', 'curation_audit_log',
    'analytics_clicks', 'analytics_pageviews', 'search_queries', 'security_audit_results',
    'mcp_usage_log',
    -- derived bulk, regenerated wholesale
    'knowledge_embeddings', 'cohort_summaries', 'budget_snapshots',
    -- harvester pipeline: output and state, rewritten every run
    'harvester_queue', 'harvester_runs', 'harvester_settings', 'harvester_keywords',
    'harvester_synonyms', 'harvester_relations',
    'grant_methods_traversal_paths', 'grant_methods_evidence', 'news_candidates',
    -- configuration: knobs, not the record
    'state_privacy_rules', 'allowed_domains', 'budget_config',
    -- intake and moderation state: decisions about data rather than data
    'access_requests', 'group_audit_dismissals', 'ingestion_records',
    -- user-submitted opinion, not a claim about the world
    'feature_suggestions', 'feature_votes', 'entity_comments',
    -- access control: covered by data_audit_log; the question is who granted it
    'user_roles',
    -- personal preferences
    'user_dashboard_layouts', 'working_group_dashboard_defaults',
    -- billing
    'lovable_invoices', 'lovable_user_usage', 'lovable_credit_events',
    -- mirrors of external systems: the truth lives in the system being mirrored. reporter_pi_
    -- observations is added here by 20260826140000 -- a curator cannot verify a RePORTER row, and
    -- re-fetching is how it is corrected.
    'slack_channel_members', 'slack_channel_pending', 'slack_channels', 'dandisets',
    'reporter_pi_observations',
    -- PURE LINK TABLES: foreign keys and nothing else, so no cell a human can judge -- grading them
    -- protected nothing while filling the worklist with uuids (20260822160000). This is now the
    -- ONLY reason. The old second reason -- that the guard is BEFORE UPDATE and link rows are never
    -- updated, so it could not fire here -- expired when 20260831160000 added an AFTER INSERT
    -- recorder. Provenance CAN reach these tables now; they are excluded because the cells are not
    -- worth judging, not because it cannot.
    -- grant_investigators and grant_dandisets are NOT in this group -- they carry attributes.
    'investigator_organizations', 'project_publications'
  ]::text[]
$fn$;

-- The DDL event trigger may already have guarded ingestion_records when it was created above.
-- Exclusion alone does not detach a trigger, so detach it here.
DROP TRIGGER IF EXISTS trg_enforce_field_provenance ON public.ingestion_records;
DROP TRIGGER IF EXISTS trg_record_field_provenance ON public.ingestion_records;
SELECT public.provenance_attach_all() AS provenance_triggers_newly_attached;

-- ── 7. Promotion ─────────────────────────────────────────────────────────────────────────────
/** Promote one ingestion record into the domain tables, in one transaction. Idempotent: a re-run
 *  updates the deployment in place and replaces its links, so correcting a payload and promoting
 *  again is how a correction lands. Anything the promoter could not resolve is added to the
 *  record's review_flags instead of being guessed. */
CREATE OR REPLACE FUNCTION public.promote_ingestion_record(_record_id uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
DECLARE
  _r     public.ingestion_records;
  _p     jsonb;
  _grant uuid;
  _dep   uuid;
  _dm    uuid;
  _name  text;
  _flags text[] := '{}';
  _claims jsonb := nullif(current_setting('request.jwt.claims', true), '')::jsonb;
BEGIN
  -- Curators and admins, the service role, or the SQL editor (no JWT at all, as for a migration).
  IF NOT (public.is_curator_or_admin(auth.uid())
          OR coalesce(_claims ->> 'role', '') = 'service_role'
          OR _claims IS NULL) THEN
    RAISE EXCEPTION 'Only curators, admins or the service role can promote ingestion records';
  END IF;

  SELECT * INTO _r FROM public.ingestion_records WHERE id = _record_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'No ingestion record %', _record_id;
  END IF;
  IF _r.status = 'rejected' THEN
    RAISE EXCEPTION 'Ingestion record % (%) was rejected at review and cannot be promoted', _r.id, _r.source_locator;
  END IF;
  IF _r.record_kind <> 'sensor_deployment' THEN
    RAISE EXCEPTION 'No promoter for record_kind %', _r.record_kind;
  END IF;
  _p := _r.payload;

  IF nullif(_p ->> 'grant_number', '') IS NOT NULL THEN
    -- grants.grant_number may still carry an application-type prefix (1U01...); payloads never do.
    SELECT id INTO _grant FROM public.grants
     WHERE regexp_replace(grant_number, '^[0-9]', '') = _p ->> 'grant_number'
     ORDER BY grant_number LIMIT 1;
    IF _grant IS NULL THEN
      RAISE EXCEPTION 'Ingestion record % (%): grant % is not in grants. Fix the payload or set grant_match to unresolved',
        _r.id, _r.source_locator, _p ->> 'grant_number';
    END IF;
  END IF;

  INSERT INTO public.sensor_deployments AS d (
    grant_id, award_label, grant_match, grant_note, label_as_named, system_kind, presenter_role,
    presenter_present, verify_note, manufacturer_recorded, manufacturer_hq_recorded, model_recorded,
    model_status, measures_recorded, source_id, source_locator, ingestion_record_id)
  VALUES (
    _grant, _p ->> 'award_label', _p ->> 'grant_match', nullif(_p ->> 'grant_note', ''),
    _p ->> 'label_as_named', _p ->> 'system_kind', nullif(_p ->> 'presenter_role', ''),
    (_p ->> 'presenter_present')::boolean, nullif(_p ->> 'verify_note', ''),
    nullif(_p ->> 'manufacturer_recorded', ''), nullif(_p ->> 'manufacturer_hq_recorded', ''),
    nullif(_p ->> 'model_recorded', ''), _p ->> 'model_status', nullif(_p ->> 'measures_recorded', ''),
    _r.source_id, _r.source_locator, _r.id)
  ON CONFLICT (award_label, label_as_named) DO UPDATE SET
    grant_id = excluded.grant_id, grant_match = excluded.grant_match, grant_note = excluded.grant_note,
    system_kind = excluded.system_kind, presenter_role = excluded.presenter_role,
    presenter_present = excluded.presenter_present, verify_note = excluded.verify_note,
    manufacturer_recorded = excluded.manufacturer_recorded,
    manufacturer_hq_recorded = excluded.manufacturer_hq_recorded,
    model_recorded = excluded.model_recorded, model_status = excluded.model_status,
    measures_recorded = excluded.measures_recorded, source_id = excluded.source_id,
    source_locator = excluded.source_locator, ingestion_record_id = excluded.ingestion_record_id
  RETURNING d.id INTO _dep;

  -- Catalogue links: by model name, then alias. A name the catalogue lacks is flagged, not invented.
  DELETE FROM public.sensor_deployment_devices WHERE deployment_id = _dep;
  FOR _name IN SELECT jsonb_array_elements_text(coalesce(_p -> 'device_models', '[]'::jsonb)) LOOP
    SELECT id INTO _dm FROM public.device_models
     WHERE model_name = _name OR _name = ANY (aliases)
     ORDER BY (model_name = _name) DESC, created_at LIMIT 1;
    IF _dm IS NULL THEN
      _flags := _flags || ('device_not_in_catalogue:' || _name);
    ELSE
      INSERT INTO public.sensor_deployment_devices VALUES (_dep, _dm) ON CONFLICT DO NOTHING;
    END IF;
  END LOOP;

  -- Properties: an unknown key fails the foreign key, and a mis-kinded one fails the kind trigger.
  DELETE FROM public.sensor_deployment_properties WHERE deployment_id = _dep;
  INSERT INTO public.sensor_deployment_properties (deployment_id, property_key, role)
  SELECT _dep, k, 'observes' FROM jsonb_array_elements_text(coalesce(_p -> 'observes', '[]'::jsonb)) k
  UNION
  SELECT _dep, k, 'actuates' FROM jsonb_array_elements_text(coalesce(_p -> 'actuates', '[]'::jsonb)) k;

  UPDATE public.ingestion_records
     SET status = 'promoted', promoted_table = 'sensor_deployments', promoted_id = _dep,
         promoted_at = now(),
         review_flags = coalesce((SELECT array_agg(DISTINCT f ORDER BY f)
                                    FROM unnest(review_flags || _flags) f), '{}')
   WHERE id = _r.id;

  RETURN jsonb_build_object('ok', true, 'record_id', _r.id, 'source_locator', _r.source_locator,
                            'deployment_id', _dep, 'new_flags', to_jsonb(_flags));
END;
$fn$;

/** Promote every record of a source that was not rejected. Returns how many were promoted. */
CREATE OR REPLACE FUNCTION public.promote_ingestion_source(_slug text)
RETURNS int LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
DECLARE
  _id uuid;
  _n  int := 0;
BEGIN
  FOR _id IN
    SELECT r.id FROM public.ingestion_records r
      JOIN public.ingestion_sources s ON s.id = r.source_id
     WHERE s.slug = _slug AND r.status <> 'rejected'
     ORDER BY r.source_locator
  LOOP
    PERFORM public.promote_ingestion_record(_id);
    _n := _n + 1;
  END LOOP;
  RETURN _n;
END;
$fn$;

REVOKE ALL ON FUNCTION public.promote_ingestion_record(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.promote_ingestion_source(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.promote_ingestion_record(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.promote_ingestion_source(text) TO authenticated, service_role;

COMMENT ON FUNCTION public.promote_ingestion_record(uuid) IS
  'Writes one ingestion record into the domain tables for its record_kind (today: sensor_deployment -> sensor_deployments + links), linking the row back to the record and source. Idempotent; re-promote after correcting a payload. Unresolvable catalogue names become review_flags. Curators, admins, service role or SQL editor only.';
